- name: New_Plastic_Feed_schedule
  cron: "*/10 * * * *"
  data:
    "agg": "average"
    "start_time": "2h-ago"
    "end_time": "now"
    "gran": "1m"
    "threshold_inscrew": 10
    "threshold_Vpump": 3
    "threshold_N2circ": 90
    "threshold_cond_pump": 10
    "threshold_fg_temp": 100
    "ncg_density": 1.6
    "NCGf": "2s=P10_EKG_BF001_MFLW01:M_MID"
    "NCGb1": "2s=P01_EKG_BF604:M_MID"
    "NCGb2": "2s=P02_EKG_BF604:M_MID"
    "NCGb3": "2s=P03_EKG_BF604:M_MID"
    "NCGb4": "2s=P04_EKG_BF604:M_MID"
    "LO_M1": "2s=P11_EGG_BF924_MFLW01:M_MID"
    "LO_M2": "2s=P12_EGG_BF974_MFLW01:M_MID"
    "HO1": "2s=P01_EGG_BF102_MFLW01:M_MID"
    "HO2": "2s=P02_EGG_BF202_MFLW01:M_MID"
    "HO3": "2s=P03_EGG_BF302_MFLW01:M_MID"
    "HO4": "2s=P04_EGG_BF402_MFLW01:M_MID"
    "HO_cond1": "2s=P01_EGG_BF103_MFLW01:M_MID"
    "HO_cond2": "2s=P02_EGG_BF203_MFLW01:M_MID"
    "HO_cond3": "2s=P03_EGG_BF303_MFLW01:M_MID"
    "HO_cond4": "2s=P04_EGG_BF403_MFLW01:M_MID"
    "W_M1": "2s=P11_GNK_BF925_MFLW01:M_MID"
    "W_M2": "2s=P12_GNK_BF975_MFLW01:M_MID"
    "Y3Fflow1": "2s=P01_EGG_BF101_MFLW01:M_MID"
    "Y3Fflow2": "2s=P02_EGG_BF201_MFLW01:M_MID"
    "Y3Fflow3": "2s=P03_EGG_BF301_MFLW01:M_MID"
    "Y3Fflow4": "2s=P04_EGG_BF401_MFLW01:M_MID"
    "YFeedIn1": "2s=P01EAC01GL001M101:M_HAST"
    "YFeedIn2": "2s=P02EAC02GL001M201:M_HAST"
    "YFeedIn3": "2s=P03EAC03GL001M301:M_HAST"
    "YFeedIn4": "2s=P04EAC04GL001M401:M_HAST"
    "Vpump1_old":   "2s=P01_EGG_QN120:M_POS"
    "Vpump2_old":   "2s=P02_EGG_QN220:M_POS"
    "Vpump3_old":   "2s=P03_EGG_QN320:M_POS"
    "Vpump4_old":   "2s=P04_EGG_QN420:M_POS"
    "Vpump1_new":   "2s=P01_EGG_QN120A:M_POS"
    "Vpump2_new":   "2s=P02_EGG_QN220A:M_POS"
    "Vpump3_new":   "2s=P03_EGG_QN320A:M_POS"
    "Vpump4_new":   "2s=P04_EGG_QN420A:M_POS"
    "N2circ1":  "2s=P01_QJB_QN152:M_POS"
    "N2circ2":  "2s=P02_QJB_QN252:M_POS"
    "N2circ3":  "2s=P03_QJB_QN352:M_POS"
    "N2circ4":  "2s=P04_QJB_QN452:M_POS"
    "cond_pump1": "2s=P01_EGG_GP101:M_SPD"
    "cond_pump2": "2s=P02_EGG_GP201:M_SPD"
    "cond_pump3": "2s=P03_EGG_GP301:M_SPD"
    "cond_pump4": "2s=P04_EGG_GP401:M_SPD"
    "YT_FGIN1": "2s=P01_RAA_TRC101_102_MTMP01:M_MID"
    "YT_FGIN2": "2s=P02_RAA_TRC201_202_MTMP01:M_MID"
    "YT_FGIN3": "2s=P03_RAA_TRC301_302_MTMP01:M_MID"
    "YT_FGIN4": "2s=P04_RAA_TRC401_402_MTMP01:M_MID"
